[program:fastapi_server]
directory=/happy_app
command=/usr/local/bin/gunicorn -c /happy_app/deploy/gunicorn.conf.py src.main:app --reload
user=root
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/supervisor/fastapi_server.out.log
stderr_logfile=/var/log/supervisor/fastapi_server.err.log