"""初始化数据库,包含系统模块相关表

Revision ID: bc765a1635ce
Revises:
Create Date: 2025-03-05 18:18:53.955945+08:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

from src.common.base_models.numeric_mixin import NumericField

# revision identifiers, used by Alembic.
revision: str = "bc765a1635ce"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bas_code_setting",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum(
                "SALE_ORDER",
                "SALE_QUOTATION",
                "SALE_CONTRACT",
                "PURCHASE_ORDER",
                "PURCHASE_RETURN",
                "PURCHASE_CONTRACT",
                "INBOUND",
                "OUTBOUND",
                "ADJUSTMENT",
                "RETURN",
                "FIN_RECEIVABLE",
                "FIN_COLLECTION",
                "FIN_PAYABLE",
                "FIN_PAYMENT",
                "FIN_VOUCHER",
                "FIN_ANALYSIS",
                "FIN_BUDGET",
                "FIN_FORECAST",
                "OTHER",
                name="documenttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "date_rule",
            sa.Enum("YYYYMMDD", "YYYYMM", "YYYY", "NONE", name="codegenerationrule"),
            nullable=False,
        ),
        sa.Column(
            "reset_frequency",
            sa.Enum("DAILY", "MONTHLY", "YEARLY", "NEVER", name="coderesetfrequency"),
            nullable=False,
        ),
        sa.Column("prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("suffix_length", sa.Integer(), nullable=False),
        sa.Column("placeholder", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_type"),
    )
    with op.batch_alter_table("bas_code_setting", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bas_code_setting_id"), ["id"], unique=False
        )

    op.create_table(
        "code_trace",
        sa.Column(
            "doc_type",
            sa.Enum(
                "SALE_ORDER",
                "SALE_QUOTATION",
                "SALE_CONTRACT",
                "PURCHASE_ORDER",
                "PURCHASE_RETURN",
                "PURCHASE_CONTRACT",
                "INBOUND",
                "OUTBOUND",
                "ADJUSTMENT",
                "RETURN",
                "FIN_RECEIVABLE",
                "FIN_COLLECTION",
                "FIN_PAYABLE",
                "FIN_PAYMENT",
                "FIN_VOUCHER",
                "FIN_ANALYSIS",
                "FIN_BUDGET",
                "FIN_FORECAST",
                "OTHER",
                name="documenttype",
            ),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("current_sequence", sa.Integer(), nullable=False),
        sa.Column("classify_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("code_trace", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_code_trace_id"), ["id"], unique=False)

    op.create_table(
        "demo",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("tenant_id", sa.Integer(), nullable=True, comment="租户ID"),
        sa.Column(
            "order_no", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "customer_name", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "total_amount",
            NumericField(precision=18, scale=2),
            nullable=True,
        ),
        sa.Column(
            "tax_amount",
            NumericField(precision=18, scale=2),
            nullable=True,
        ),
        sa.Column(
            "discount_amount",
            NumericField(precision=18, scale=2),
            nullable=True,
        ),
        sa.Column(
            "tax_rate",
            NumericField(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "discount_rate",
            NumericField(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_no"),
    )
    with op.batch_alter_table("demo", schema=None) as batch_op:
        batch_op.create_index("idx_demo_order_no", ["order_no"], unique=False)
        batch_op.create_index(batch_op.f("ix_demo_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_demo_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "sys_dept",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parent_id", sa.BIGINT(), nullable=True),
        sa.Column(
            "tree_path",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            comment="节点路径",
        ),
        sa.Column("level", sa.Integer(), nullable=False, comment="节点层级"),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["sys_dept.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("sys_dept", schema=None) as batch_op:
        batch_op.create_index("idx_dept_name", ["name"], unique=False)
        batch_op.create_index("idx_dept_parent_id", ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_dept_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sys_dept_tree_path"), ["tree_path"], unique=False
        )

    op.create_table(
        "sys_factory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column(
            "factory_name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "factory_alias", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("logo", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("sales_type", sa.Integer(), nullable=False),
        sa.Column(
            "standard_money",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sys_factory", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sys_factory_id"), ["id"], unique=False)

    op.create_table(
        "sys_login_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "trace_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "user_uuid", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("ip", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("os", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("browser", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("device", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("msg", sa.Text(), nullable=False),
        sa.Column("login_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sys_login_log", schema=None) as batch_op:
        batch_op.create_index("idx_login_log_user_uuid", ["user_uuid"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_login_log_id"), ["id"], unique=False)

    op.create_table(
        "sys_notification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("SYSTEM", "USER", "TASK", "ALERT", name="notificationtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("UNREAD", "READ", name="notificationstatus"),
            nullable=False,
        ),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.String(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sys_notification", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sys_notification_id"), ["id"], unique=False
        )

    op.create_table(
        "sys_notification_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type", sa.Enum("SYSTEM", "USER", name="notificationtype"), nullable=False
        ),
        sa.Column("title_template", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "content_template", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "condition",
            sa.Enum("SUCCESS", "FAILURE", "ALWAYS", name="notificationcondition"),
            nullable=False,
        ),
        sa.Column(
            "recipient_id_field", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "path", "method", "type", name="uq_notification_rule_path_method_type"
        ),
        comment="通知规则配置表",
    )
    with op.batch_alter_table("sys_notification_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sys_notification_rules_id"), ["id"], unique=False
        )

    op.create_table(
        "sys_opera_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "trace_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "method", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("ip", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column(
            "user_agent", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("os", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column(
            "browser", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("device", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column(
            "status", sa.Enum("FAIL", "SUCCESS", name="operalogstatus"), nullable=False
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("msg", sa.Text(), nullable=True),
        sa.Column("cost_time", sa.Float(), nullable=False),
        sa.Column("opera_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sys_opera_log", schema=None) as batch_op:
        batch_op.create_index(
            "idx_opera_log_composite",
            ["username", "status", "opera_time"],
            unique=False,
        )
        batch_op.create_index("idx_opera_log_status", ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_opera_log_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sys_opera_log_opera_time"), ["opera_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sys_opera_log_trace_id"), ["trace_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sys_opera_log_username"), ["username"], unique=False
        )

    op.create_table(
        "sys_permission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parent_id", sa.BIGINT(), nullable=True),
        sa.Column(
            "tree_path",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            comment="节点路径",
        ),
        sa.Column("level", sa.Integer(), nullable=False, comment="节点层级"),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "type",
            sa.Enum("MENU", "API", "DATA", name="permissiontype"),
            nullable=False,
        ),
        sa.Column(
            "route_path", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column(
            "route_component",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column(
            "route_redirect",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
        sa.Column(
            "route_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "route_title", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "route_icon", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("route_hidden", sa.Boolean(), nullable=False),
        sa.Column("route_keep_alive", sa.Boolean(), nullable=False),
        sa.Column("route_always_show", sa.Boolean(), nullable=False),
        sa.Column(
            "api_path", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column(
            "api_method", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column(
            "perm_code", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["sys_permission.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("sys_permission", schema=None) as batch_op:
        batch_op.create_index("idx_permission_api_path", ["api_path"], unique=False)
        batch_op.create_index("idx_permission_parent_id", ["parent_id"], unique=False)
        batch_op.create_index("idx_permission_route_path", ["route_path"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_permission_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sys_permission_tree_path"), ["tree_path"], unique=False
        )

    op.create_table(
        "sys_role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="rolestatus"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("sys_role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sys_role_id"), ["id"], unique=False)

    op.create_table(
        "sys_tenant",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="tenantstatus"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sys_tenant", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sys_tenant_id"), ["id"], unique=False)

    op.create_table(
        "demo_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("demo_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "product_name", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "product_code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "quantity",
            NumericField(precision=15, scale=4),
            nullable=True,
        ),
        sa.Column(
            "unit_price",
            NumericField(precision=18, scale=4),
            nullable=True,
        ),
        sa.Column(
            "total_price",
            NumericField(precision=18, scale=2),
            nullable=True,
        ),
        sa.Column("soft_delete", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["demo_id"],
            ["demo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_code", "soft_delete", name="uq_demo_item_product_code_soft_delete"
        ),
        sa.UniqueConstraint(
            "product_name", "soft_delete", name="uq_demo_item_product_name_soft_delete"
        ),
    )
    with op.batch_alter_table("demo_item", schema=None) as batch_op:
        batch_op.create_index("idx_demo_item_demo_id", ["demo_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_demo_item_id"), ["id"], unique=False)

    op.create_table(
        "sys_permission_rule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("permission_id", sa.BIGINT(), nullable=False),
        sa.Column("rule", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ENABLE", "DISABLE", name="permissionrulestatus"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["sys_permission.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sys_permission_rule", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sys_permission_rule_id"), ["id"], unique=False
        )

    op.create_table(
        "sys_role_permission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.BIGINT(), nullable=False),
        sa.Column("permission_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["sys_permission.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["sys_role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id"),
    )
    with op.batch_alter_table("sys_role_permission", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sys_role_permission_id"), ["id"], unique=False
        )

    op.create_table(
        "sys_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("dept_id", sa.BIGINT(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "avatar", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="userstatus"),
            nullable=False,
        ),
        sa.Column(
            "emp_type",
            sa.Enum(
                "ADMIN", "STAFF", "SALES", "FINANCE", "HR", "IT", name="useremptype"
            ),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.Column("is_user", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_multi_login", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "home_path", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("salt", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.ForeignKeyConstraint(["dept_id"], ["sys_dept.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sys_user", schema=None) as batch_op:
        batch_op.create_index("idx_user_dept_id", ["dept_id"], unique=False)
        batch_op.create_index("idx_user_uuid", ["uuid"], unique=False)
        batch_op.create_index(batch_op.f("ix_sys_user_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sys_user_username"), ["username"], unique=True
        )

    op.create_table(
        "sys_factory_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("factory_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["factory_id"], ["sys_factory.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["sys_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "factory_id", name="uq_factory_user"),
    )
    with op.batch_alter_table("sys_factory_user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sys_factory_user_id"), ["id"], unique=False
        )

    op.create_table(
        "sys_user_role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("role_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["sys_role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["sys_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    with op.batch_alter_table("sys_user_role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sys_user_role_id"), ["id"], unique=False)

    op.create_table(
        "sys_user_tenant",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=True, comment="更新时间"
        ),
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建者"),
        sa.Column("updated_by", sa.Integer(), nullable=True, comment="更新者"),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("tenant_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["sys_tenant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["sys_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tenant_id", name="uq_user_tenant"),
    )
    with op.batch_alter_table("sys_user_tenant", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sys_user_tenant_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sys_user_tenant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_user_tenant_id"))

    op.drop_table("sys_user_tenant")
    with op.batch_alter_table("sys_user_role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_user_role_id"))

    op.drop_table("sys_user_role")
    with op.batch_alter_table("sys_factory_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_factory_user_id"))

    op.drop_table("sys_factory_user")
    with op.batch_alter_table("sys_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_user_username"))
        batch_op.drop_index(batch_op.f("ix_sys_user_id"))
        batch_op.drop_index("idx_user_uuid")
        batch_op.drop_index("idx_user_dept_id")

    op.drop_table("sys_user")
    with op.batch_alter_table("sys_role_permission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_role_permission_id"))

    op.drop_table("sys_role_permission")
    with op.batch_alter_table("sys_permission_rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_permission_rule_id"))

    op.drop_table("sys_permission_rule")
    with op.batch_alter_table("demo_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_demo_item_id"))
        batch_op.drop_index("idx_demo_item_demo_id")

    op.drop_table("demo_item")
    with op.batch_alter_table("sys_tenant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_tenant_id"))

    op.drop_table("sys_tenant")
    with op.batch_alter_table("sys_role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_role_id"))

    op.drop_table("sys_role")
    with op.batch_alter_table("sys_permission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_permission_tree_path"))
        batch_op.drop_index(batch_op.f("ix_sys_permission_id"))
        batch_op.drop_index("idx_permission_route_path")
        batch_op.drop_index("idx_permission_parent_id")
        batch_op.drop_index("idx_permission_api_path")

    op.drop_table("sys_permission")
    with op.batch_alter_table("sys_opera_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_opera_log_username"))
        batch_op.drop_index(batch_op.f("ix_sys_opera_log_trace_id"))
        batch_op.drop_index(batch_op.f("ix_sys_opera_log_opera_time"))
        batch_op.drop_index(batch_op.f("ix_sys_opera_log_id"))
        batch_op.drop_index("idx_opera_log_status")
        batch_op.drop_index("idx_opera_log_composite")

    op.drop_table("sys_opera_log")
    with op.batch_alter_table("sys_notification_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_notification_rules_id"))

    op.drop_table("sys_notification_rules")
    with op.batch_alter_table("sys_notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_notification_id"))

    op.drop_table("sys_notification")
    with op.batch_alter_table("sys_login_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_login_log_id"))
        batch_op.drop_index("idx_login_log_user_uuid")

    op.drop_table("sys_login_log")
    with op.batch_alter_table("sys_factory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_factory_id"))

    op.drop_table("sys_factory")
    with op.batch_alter_table("sys_dept", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sys_dept_tree_path"))
        batch_op.drop_index(batch_op.f("ix_sys_dept_id"))
        batch_op.drop_index("idx_dept_parent_id")
        batch_op.drop_index("idx_dept_name")

    op.drop_table("sys_dept")
    with op.batch_alter_table("demo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_demo_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_demo_id"))
        batch_op.drop_index("idx_demo_order_no")

    op.drop_table("demo")
    with op.batch_alter_table("code_trace", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_code_trace_id"))

    op.drop_table("code_trace")
    with op.batch_alter_table("bas_code_setting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bas_code_setting_id"))

    op.drop_table("bas_code_setting")
    # ### end Alembic commands ###
